name: detect forbidden characters

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RIPGREP_VERSION: 13.0.0
      BIN_DIR: ${{ github.workspace }}/bin
      REPO_DIR: repo
      cache-version: v1
    steps:
    - id: cache-ripgrep
      uses: actions/cache@v1
      with:
        path: ${{ env.BIN_DIR }}
        key: ${{ env.cache-version }}-ripgrep-${{ env.RIPGREP_VERSION }}
    - name: install ripgrep
      if: steps.cache-ripgrep.outputs.cache-hit != 'true'
      run: |
        curl -fsSLO https://github.com/BurntSushi/ripgrep/releases/download/$RIPGREP_VERSION/ripgrep-$RIPGREP_VERSION-x86_64-unknown-linux-musl.tar.gz
        mkdir -p $BIN_DIR
        tar xvf ripgrep-$RIPGREP_VERSION-x86_64-unknown-linux-musl.tar.gz --strip=1 --no-anchor -C $BIN_DIR rg
      working-directory: ${{ runner.temp }}
    - uses: actions/checkout@v2
      with:
        path: ${{ env.REPO_DIR }}
    - name: check
      run: "! $BIN_DIR/rg -t md --vimgrep '[\u00ad\u200b]' $REPO_DIR"
